### ISSUE TITLE
 PIP window hides when using touchpad to change workspaces

### ISSUE THREAD

**Issue by IvoryJam** [bennypowers/gnome-shell-extension-firefox-pip#4]
If I use super+pgup/pgdown it comes works as expected.

If I change workspaces using the 3 finger swipe built into gnome it hides the window

Interestingly if I just use the 3 finger swipe to almost change the workspace but don't, it still hides. Using the super+pgup/pgdown it comes back up.

**Comment by bennypowers** [comment]
Huh weird
I'm guessing this is a gnome problem because I'm just setting the regular flags on the window

Can you reproduce this by right clicking a normal window's title bar to set the always on top settings?

**Comment by IvoryJam** [comment]
I sure can, looks like it's a Gnome issue, my bad! In case anyone comes across this too I'm on Gnome 44.3 Wayland where the issue exists
