### ISSUE TITLE
Extension doesn't work on Firefox v120

### ISSUE THREAD

**Issue by Scotty-Trees** [bennypowers/gnome-shell-extension-firefox-pip#7]
Greetings,

Firefox just updated on Nov 21 to version 120. However now the extension no longer puts the window on top anymore. Tried a few videos on YouTube and Twitch and sadly it no longer works, the window hides behind the main window. I don't know what Firefox v120 changed, but if you need any logs or more info please let me know. This was tested on Fedora 39 with Gnome 45.1 under Wayland. Thank you

Edit: I forgot to mention in the v120 changelog, Firefox mentions this: "The Picture-in-Picture feature has been improved in Firefox 120 with a new corner-snapping feature that can be activated when holding the Linux Shift key while moving the PiP window. " So that may be the reason why the extension no longer works, FYI.

**Comment by bennypowers** [comment]
i'll take a look when 120 lands on flathub

**Comment by Scotty-Trees** [comment]
> i'll take a look when 120 lands on flathub

It landed on flathub 7 days ago, so a quick `flatpak update` should pull in the latest Firefox for ya btw.

**Comment by bennypowers** [comment]
huh yeah ok i guess i never got around to switching from the fedora flatpak store

in that case i'll look into this b.n. tomorrow. i heard some rumours that 120 builds this feature in so you might be able to get satisfaction by disabling the extension and going spelunking in about:config

thanks for the report!

**Comment by Scotty-Trees** [comment]
Yeah no worries, I moved some of my Fedora flatpaks over to Flathub since updates were a bit quicker as well. I have turned off the extension on v120 for now, as the window still hides itself, but I'll try to look for any about:config setting and see if I can figure anything out, but until then thanks for the quick replies and I do appreciate your awesome little extension very much btw so thanks for making it!

**Comment by bennypowers** [comment]
well then yeah switching to the flathub version was truly unpleasant. there goes my ff sync account, and the flathub version wouldn't load pages or extensions, so i guess i'll be waiting until fedora updates. should be soon

**Comment by Scotty-Trees** [comment]
If it helps at all, v120 is already in the main Fedora rpm repo, but I don't know how that may or may not affect your sync account abilities. If it's not updated soon, I'd imagine it'll probably be updated sometime after the Thanksgiving break that many people have this week in the US.

**Comment by joshbode** [comment]
I've got Firefox Beta installed via Flatpak (`flathub-beta`) and using the Looking Glass evaluator (Alt-F2, `lg`), I can see that the two checks on this line fail:

https://github.com/bennypowers/gnome-shell-extension-firefox-pip/blob/8bacb47a362eb41d0a6604b92342d07f7da30099/extension.js#L30

My install yields this for the following properties of the PiP window:
- `window.get_wm_class()` is `"firefox-beta"`
- `window.get_sandboxed_app_id()` is `"org.mozilla.firefox"`
- `window.get_title()` is `"Picture-in-Picture"`

If I manually manipulate the window, e.g.
```javascript
window.raise_and_make_recent();
window.make_above();
window.stick();
```
then it works (i.e. the PiP window is always on top), so it might be as simple as extending the matching on the `wm_class`/`sandboxed_app_id`

**Comment by bennypowers** [comment]
version 8 is under review, which includes a potential fix for this

**Comment by bennypowers** [comment]
8 is approved. please advice if version 8 solves the problem

**Comment by Scotty-Trees** [comment]
> 8 is approved. please advice if version 8 solves the problem

Running version 8 works perfectly again on Fedora 39 Gnome. Thanks very much for the update!
